### PR TITLE
Add travis configuration

### PR DESCRIPTION
**Pull request by eleanorakh**
This adds the configuration required to set up automatic builds on TravisCI.

### CODE REVIEW

**Comment by eleanorakh** [comment]
[Run builds for raca on Travis CI](https://trello.com/c/1QyE8zaX/7693-run-builds-for-raca-on-travis-ci)

**Comment by keithpitty** [comment]
@eleanorakh has this run on Travis CI?

**Comment by yob** [comment]
> has this run on Travis CI?

looks like it has

raca-travis

**Comment by keithpitty** [comment]
🤦‍♂️

**Comment by keithpitty** [comment]
👍

**Pull request merged**
